/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'website-pages': WebsitePage;
    'component-pages': ComponentPage;
    foundations: Foundation;
    articles: Article;
    releases: Release;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'website-pages': WebsitePagesSelect<false> | WebsitePagesSelect<true>;
    'component-pages': ComponentPagesSelect<false> | ComponentPagesSelect<true>;
    foundations: FoundationsSelect<false> | FoundationsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-navigation': SiteNavigation;
  };
  globalsSelect: {
    'site-navigation': SiteNavigationSelect<false> | SiteNavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-pages".
 */
export interface WebsitePage {
  id: number;
  title: string;
  /**
   * Use "home" for the website home page. Other slugs render at /[slug]. Do not include a leading slash.
   */
  slug: string;
  /**
   * Choose whether this website page uses the documentation sidebar.
   */
  layout: 'docs-sidebar' | 'no-sidebar' | 'custom';
  status: 'draft' | 'published';
  pageType: 'home' | 'generic' | 'tokens' | 'patterns' | 'changelog' | 'custom';
  hero: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  /**
   * Cards shown in the foundational visual styles section on the home page.
   */
  visualCards?:
    | {
        title: string;
        label: string;
        tone: 'orange' | 'light' | 'green' | 'plain';
        id?: string | null;
      }[]
    | null;
  intro?: {
    eyebrow?: string | null;
    title?: string | null;
    cardTitle?: string | null;
    cardBody?: string | null;
    body?:
      | {
          heading?: string | null;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Generic page body sections rendered on /[slug] pages.
   */
  sections?:
    | {
        eyebrow?: string | null;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  changelog?: {
    dateLabel?: string | null;
    title?: string | null;
    summary?: string | null;
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-pages".
 */
export interface ComponentPage {
  id: number;
  name: string;
  /**
   * URL segment used by /components/[slug], for example accordion.
   */
  slug: string;
  status: 'draft' | 'published';
  componentStatus: 'Draft' | 'Ready';
  platform: 'Desktop' | 'Mobile' | 'Shared';
  description: string;
  importName: string;
  packageName: string;
  /**
   * Desktop guidance shown below the live preview. Use headings, lists, callouts, and images — this replaces the old anatomy/usage/accessibility lists.
   */
  desktopContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Mobile guidance shown below the mobile preview. Leave empty for desktop-only components.
   */
  mobileContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "foundations".
 */
export interface Foundation {
  id: number;
  name: string;
  /**
   * URL segment used by /foundation/[slug], for example color.
   */
  slug: string;
  status: 'draft' | 'published';
  eyebrow?: string | null;
  description: string;
  /**
   * Foundation guidance shown below the intro. Use headings, lists, callouts, and images — this replaces the old per-section title/body fields.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional list of CSS variables or token names relevant to this foundation.
   */
  tokenReferences?:
    | {
        name: string;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL-safe article identifier, for example design-principles.
   */
  slug: string;
  /**
   * Short summary for cards, search results, and previews.
   */
  excerpt?: string | null;
  status: 'draft' | 'published';
  category: 'guideline' | 'foundation' | 'component' | 'pattern' | 'announcement';
  heroImage?: (number | null) | Media;
  relatedComponents?:
    | {
        name: string;
        platform: 'desktop' | 'mobile' | 'shared';
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  /**
   * Release label, for example Brankas 2.2 or @brankas/react 0.3.0.
   */
  version: string;
  title: string;
  /**
   * Public URL slug. For example, brankas-2-2 renders at /change-log/brankas-2-2.
   */
  slug: string;
  summary: string;
  status: 'draft' | 'published';
  releaseDate: string;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'website-pages';
        value: number | WebsitePage;
      } | null)
    | ({
        relationTo: 'component-pages';
        value: number | ComponentPage;
      } | null)
    | ({
        relationTo: 'foundations';
        value: number | Foundation;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-pages_select".
 */
export interface WebsitePagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?: T;
  status?: T;
  pageType?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  visualCards?:
    | T
    | {
        title?: T;
        label?: T;
        tone?: T;
        id?: T;
      };
  intro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        cardTitle?: T;
        cardBody?: T;
        body?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
            };
      };
  sections?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  changelog?:
    | T
    | {
        dateLabel?: T;
        title?: T;
        summary?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-pages_select".
 */
export interface ComponentPagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  componentStatus?: T;
  platform?: T;
  description?: T;
  importName?: T;
  packageName?: T;
  desktopContent?: T;
  mobileContent?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "foundations_select".
 */
export interface FoundationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  eyebrow?: T;
  description?: T;
  content?: T;
  tokenReferences?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  status?: T;
  category?: T;
  heroImage?: T;
  relatedComponents?:
    | T
    | {
        name?: T;
        platform?: T;
        id?: T;
      };
  content?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  version?: T;
  title?: T;
  slug?: T;
  summary?: T;
  status?: T;
  releaseDate?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  coverImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation".
 */
export interface SiteNavigation {
  id: number;
  brand: {
    homeHref: string;
    brandName: string;
    productName: string;
  };
  /**
   * Main navbar links shown in the top header.
   */
  topNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sidebar groups and links shown in the documentation shell.
   */
  sidebarSections?:
    | {
        title: string;
        items: {
          label: string;
          href: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation_select".
 */
export interface SiteNavigationSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        homeHref?: T;
        brandName?: T;
        productName?: T;
      };
  topNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  sidebarSections?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}